version: '3.7'

services:
  postgres:
    image: postgres:12
    ports:
      - '5432:5432'
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=seed
