version: '3.5'

services:
  node:
    build: 
      context: .
      dockerfile: node.dockerfile
    volumes: 
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    depends_on: 
      - postgres
    networks:
      - app-network
    env_file: 
      - ./env/dev.env
    restart: always

  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    networks: 
      - app-network
    env_file:
      - ./env/postgres.env

networks:
  app-network:
    driver: bridge