version: '3.7'

services:
  postgres:
    image: postgres:12
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=music-sheet
  postgres-test:
    image: postgres:12
    ports:
      - '5433:5432'
    volumes:
      - pgtestdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=music-sheet-test

volumes:
  pgdata:
    driver: local
  pgtestdata:
    driver: local
